package com.kyweb.vo;

public class QuartzVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.quartz_time
     *
     * @mbggenerated
     */
    private String quartzTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.message_type
     *
     * @mbggenerated
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.message_target
     *
     * @mbggenerated
     */
    private String messageTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.message_status
     *
     * @mbggenerated
     */
    private String messageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.message_send_time
     *
     * @mbggenerated
     */
    private String messageSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.insert_time
     *
     * @mbggenerated
     */
    private String insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.id
     *
     * @return the value of tb_quartz.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.id
     *
     * @param id the value for tb_quartz.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.message
     *
     * @return the value of tb_quartz.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.message
     *
     * @param message the value for tb_quartz.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.quartz_time
     *
     * @return the value of tb_quartz.quartz_time
     *
     * @mbggenerated
     */
    public String getQuartzTime() {
        return quartzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.quartz_time
     *
     * @param quartzTime the value for tb_quartz.quartz_time
     *
     * @mbggenerated
     */
    public void setQuartzTime(String quartzTime) {
        this.quartzTime = quartzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.user_name
     *
     * @return the value of tb_quartz.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.user_name
     *
     * @param userName the value for tb_quartz.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.message_type
     *
     * @return the value of tb_quartz.message_type
     *
     * @mbggenerated
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.message_type
     *
     * @param messageType the value for tb_quartz.message_type
     *
     * @mbggenerated
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.message_target
     *
     * @return the value of tb_quartz.message_target
     *
     * @mbggenerated
     */
    public String getMessageTarget() {
        return messageTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.message_target
     *
     * @param messageTarget the value for tb_quartz.message_target
     *
     * @mbggenerated
     */
    public void setMessageTarget(String messageTarget) {
        this.messageTarget = messageTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.message_status
     *
     * @return the value of tb_quartz.message_status
     *
     * @mbggenerated
     */
    public String getMessageStatus() {
        return messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.message_status
     *
     * @param messageStatus the value for tb_quartz.message_status
     *
     * @mbggenerated
     */
    public void setMessageStatus(String messageStatus) {
        this.messageStatus = messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.message_send_time
     *
     * @return the value of tb_quartz.message_send_time
     *
     * @mbggenerated
     */
    public String getMessageSendTime() {
        return messageSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.message_send_time
     *
     * @param messageSendTime the value for tb_quartz.message_send_time
     *
     * @mbggenerated
     */
    public void setMessageSendTime(String messageSendTime) {
        this.messageSendTime = messageSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.insert_time
     *
     * @return the value of tb_quartz.insert_time
     *
     * @mbggenerated
     */
    public String getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.insert_time
     *
     * @param insertTime the value for tb_quartz.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(String insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz.update_time
     *
     * @return the value of tb_quartz.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz.update_time
     *
     * @param updateTime the value for tb_quartz.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}